# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ant.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='ant.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\tant.proto\"g\n\nAntRequest\x12\x0c\n\x04\x66unc\x18\x01 \x01(\t\x12\x14\n\x0crequest_data\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x14\n\x0c\x63hannel_name\x18\x04 \x01(\t\x12\x10\n\x08\x64\x61g_name\x18\x05 \x01(\t\"?\n\x0b\x41ntResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x15\n\rresponse_data\x18\x03 \x01(\t22\n\x0c\x41ntRpcServer\x12\"\n\x03run\x12\x0b.AntRequest\x1a\x0c.AntResponse\"\x00\x62\x06proto3'
)

_ANTREQUEST = _descriptor.Descriptor(
    name='AntRequest',
    full_name='AntRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='func', full_name='AntRequest.func', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='request_data', full_name='AntRequest.request_data', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='token', full_name='AntRequest.token', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='channel_name', full_name='AntRequest.channel_name', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='dag_name', full_name='AntRequest.dag_name', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=13,
    serialized_end=116,
)

_ANTRESPONSE = _descriptor.Descriptor(
    name='AntResponse',
    full_name='AntResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='code', full_name='AntResponse.code', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='msg', full_name='AntResponse.msg', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='response_data', full_name='AntResponse.response_data', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=118,
    serialized_end=181,
)

DESCRIPTOR.message_types_by_name['AntRequest'] = _ANTREQUEST
DESCRIPTOR.message_types_by_name['AntResponse'] = _ANTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AntRequest = _reflection.GeneratedProtocolMessageType('AntRequest', (_message.Message,), {
    'DESCRIPTOR': _ANTREQUEST,
    '__module__': 'ant_pb2'
    # @@protoc_insertion_point(class_scope:AntRequest)
})
_sym_db.RegisterMessage(AntRequest)

AntResponse = _reflection.GeneratedProtocolMessageType('AntResponse', (_message.Message,), {
    'DESCRIPTOR': _ANTRESPONSE,
    '__module__': 'ant_pb2'
    # @@protoc_insertion_point(class_scope:AntResponse)
})
_sym_db.RegisterMessage(AntResponse)

_ANTRPCSERVER = _descriptor.ServiceDescriptor(
    name='AntRpcServer',
    full_name='AntRpcServer',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=183,
    serialized_end=233,
    methods=[
        _descriptor.MethodDescriptor(
            name='run',
            full_name='AntRpcServer.run',
            index=0,
            containing_service=None,
            input_type=_ANTREQUEST,
            output_type=_ANTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_ANTRPCSERVER)

DESCRIPTOR.services_by_name['AntRpcServer'] = _ANTRPCSERVER

# @@protoc_insertion_point(module_scope)
